pipeline {
    agent any

    environment {
        ACR_REGISTRY = 'ahmadweatheracr24486.azurecr.io'
        IMAGE_NAME   = 'skypulse-weather-dashboard'
        IMAGE_TAG    = "${BUILD_NUMBER}"
        AZURE_RG     = 'ahmad-weather-rg'
        AKS_CLUSTER  = 'ahmad-weather-aks'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AhmadMushabbir/DevSecOps-NodeJS-WeatherDashboard-AKS.git'
            }
        }

        stage('NodeJS Build & Test') {
            steps {
                dir('app') {
                    sh 'npm install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('app') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'sonar-scanner -Dsonar.projectKey=skypulse-weather-dashboard -Dsonar.sources=.'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Snyk Dependency Security Scan') {
            steps {
                dir('app') {
                    sh 'snyk test --all-projects || true'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    sh "docker build -t ${ACR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL ${ACR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }

        stage('Push Image to ACR') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'acr-credentials', usernameVariable: 'ACR_USER', passwordVariable: 'ACR_PASS')]) {
                    sh "docker login ${ACR_REGISTRY} -u ${ACR_USER} -p ${ACR_PASS}"
                    sh "docker push ${ACR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage('Helm Upgrade to AKS') {
            steps {
                withCredentials([azureServicePrincipal('azure-sp-credentials')]) {
                    sh "az aks get-credentials --resource-group ${AZURE_RG} --name ${AKS_CLUSTER} --overwrite-existing"
                    sh "helm upgrade --install skypulse skypulse-chart/ --set image.tag=${IMAGE_TAG}"
                }
            }
        }
    }

    post {
        always {
            sh 'docker logout ${ACR_REGISTRY} || true'
            cleanWs()
        }
    }
}
